import { Inter } from 'next/font/google'
import Link from 'next/link'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'learn next.js',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="./icon.png" />
      </head>
      <body className={inter.className}>
        <nav style={{
          width: "100%",
          background: "teal",
          fontSize: "50px",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          gap: "2rem"
        }}>
          <Link href="/">
            Home
          </Link>
          <Link href="/articles">
            articles
          </Link>
          <Link href="/posts">
            posts
          </Link>
        </nav>
        {children}
      </body>
    </html>
  )
}
