
export const metadata = {
    title: 'Articles',
    description: 'Generated by create next app',
}

export default function layout({ children }) {

    return (
        <>
            <h1>layout</h1>
            <div>
                {children}
            </div>
        </>
    )
}
